import { createTypes } from 'reduxsauce'

export default createTypes(
  `
  GET_CASE_ATTEMPT
  GET_CASE_SUCCESS
  
  GET_CASES_ATTEMPT
  GET_CASES_SUCCESS

  CREATE_CASE_ATTEMPT
  CREATE_CASE_SUCCESS

  GET_CASES_IMAGES_ATTEMPT
  GET_CASES_IMAGES_SUCCESS

  ADD_CASE_CATEGORY_ATTEMPT
  ADD_CASE_CATEGORY_SUCCESS

  REMOVE_CASE_CATEGORY_ATTEMPT
  REMOVE_CASE_CATEGORY_SUCCESS

  ADD_CASE_ITEM_ATTEMPT
  ADD_CASE_ITEM_SUCCESS

  REMOVE_CASE_ITEM_ATTEMPT
  REMOVE_CASE_ITEM_SUCCESS

  UPDATE_CASE_ITEM_ATTEMPT
  UPDATE_CASE_ITEM_SUCCESS

  UPDATE_CASE_STATUS_ATTEMPT
  UPDATE_CASE_STATUS_SUCCESS

  UPDATE_CASE_PRIORITIES_ATTEMPT
  UPDATE_CASE_PRIORITIES_SUCCESS

  UPDATE_CASE_ATTEMPT
  UPDATE_CASE_SUCCESS

  GET_CASE_PRICE_ATTEMPT
  GET_CASE_PRICE_SUCCESS

  UPLOAD_CASE_IMAGE_ATTEMPT
  UPLOAD_CASE_IMAGE_SUCCESS

  API_ATTEMPT
  API_SUCCESS
  API_FAILED
  `
)